### ISSUE TITLE
Batch implementation

### ISSUE THREAD

**Issue by vitalielias** [kit-data-manager/SEM-Mapping-Tool#2]
Currently this only works with single file inputs. The code should be modified to accept a zip file as an output, and output instead a zip file containing all the generated metadata documents.

**Comment by vitalielias** [comment]
The latest commit e032c9e2b02267085ab0c80a191624c993197f94 works perfectly in that it takes an input zip file and stores a zip file containing each json metadata document in the specified directory.

This new version now needs to be tested and implemented in the mapping service.

NB: a new script was created for this, and will serve as the main script from now on as the other one is simply too disorganized.

**Comment by vitalielias** [comment]
There may be problems with the new map as it's currently not finding the tiltAngle or tiltCorrection keys anymore...

Edit 2.5. 09:46: this is very likely a problem with the new map/schema. Check the map file for typos

**Comment by vitalielias** [comment]
Currently it creates a temporary directory which it then compresses to create the results zip file after creating all the json metadata documents. This could be an issue when it is run on the server as the bw cloud instance has limited memory (and storage). This should be tested. Talk to Volker with Ajay

**Comment by reetuelzajoseph** [comment]
> There may be problems with the new map as it's currently not finding the tiltAngle or tiltCorrection keys anymore...

This is not a problem with the map, but with the data cleaning part. 

What was formerly `Tilt Angle` is now called `tiltCorrectionAngle`, with a unit and value. So the data cleaning needs to be updated as per our discussion in the first week of April.
The `tiltCorrection` parameter doesn't exist anymore, so this part can be removed.

Also all the extra angle-units need to be mapped to the word degree.

**Comment by vitalielias** [comment]
Thanks for the comment and for finding the issue. I will fix it today!

Edit: fixed in eaeacb3

**Comment by vitalielias** [comment]
This has been taken care of.
